package com.example.application.utilities.classes;

public enum Color {

    PRIMARY,
    ON_PRIMARY,
    PRIMARY_CONTAINER,
    ON_PRIMARY_CONTAINER,
    SECONDARY,
    ON_SECONDARY,
    SECONDARY_CONTAINER,
    ON_SECONDARY_CONTAINER,
    TERTIARY,
    ON_TERTIARY,
    TERTIARY_CONTAINER,
    ON_TERTIARY_CONTAINER,
    ERROR,
    ERROR_CONTAINER,
    ON_ERROR,
    ON_ERROR_CONTAINER,
    BACKGROUND,
    ON_BACKGROUND,
    SURFACE,
    ON_SURFACE,
    SURFACE_VARIANT,
    ON_SURFACE_VARIANT,
    OUTLINE,
    OUTLINE_VARIANT,
    SURFACE_TINT_COLOR,
    INVERSE_SURFACE,
    INVERSE_ON_SURFACE,
    INVERSE_PRIMARY;

}
